//
//  CTCarrier+CountryCallingCode.m
//  Xhoppe
//
//  Created by Cheng Yao on 23/11/14.
//  Copyright (c) 2014 Cheng Yao. All rights reserved.
//

#import "CTCarrier+CountryCallingCode.h"

@implementation CTCarrier (CountryCallingCode)

- (NSDictionary *)callingCodeMap
{
    return @{
             @"AD" : @"+376",
             @"AE" : @"+971",
             @"AF" : @"+93",
             @"AG" : @"+1268",
             @"AI" : @"+1264",
             @"AL" : @"+355",
             @"AM" : @"+374",
             @"AN" : @"+599",
             @"AO" : @"+244",
             @"AQ" : @"+672",
             @"AR" : @"+54",
             @"AS" : @"+1684",
             @"AT" : @"+43",
             @"AU" : @"+61",
             @"AW" : @"+297",
             @"AZ" : @"+994",
             @"BA" : @"+387",
             @"BB" : @"+1246",
             @"BD" : @"+880",
             @"BE" : @"+32",
             @"BF" : @"+226",
             @"BG" : @"+359",
             @"BH" : @"+973",
             @"BI" : @"+257",
             @"BJ" : @"+229",
             @"BL" : @"+590",
             @"BM" : @"+1441",
             @"BN" : @"+673",
             @"BO" : @"+591",
             @"BR" : @"+55",
             @"BS" : @"+1242",
             @"BT" : @"+975",
             @"BW" : @"+267",
             @"BY" : @"+375",
             @"BZ" : @"+501",
             @"CA" : @"+1",
             @"CC" : @"+61",
             @"CD" : @"+243",
             @"CF" : @"+236",
             @"CG" : @"+242",
             @"CH" : @"+41",
             @"CI" : @"+225",
             @"CK" : @"+682",
             @"CL" : @"+56",
             @"CM" : @"+237",
             @"CN" : @"+86",
             @"CO" : @"+57",
             @"CR" : @"+506",
             @"CU" : @"+53",
             @"CV" : @"+238",
             @"CX" : @"+61",
             @"CY" : @"+357",
             @"CZ" : @"+420",
             @"DE" : @"+49",
             @"DJ" : @"+253",
             @"DK" : @"+45",
             @"DM" : @"+1767",
             @"DO" : @"+1809",
             @"DZ" : @"+213",
             @"EC" : @"+593",
             @"EE" : @"+372",
             @"EG" : @"+20",
             @"ER" : @"+291",
             @"ES" : @"+34",
             @"ET" : @"+251",
             @"FI" : @"+358",
             @"FJ" : @"+679",
             @"FK" : @"+500",
             @"FM" : @"+691",
             @"FO" : @"+298",
             @"FR" : @"+33",
             @"GA" : @"+241",
             @"GB" : @"+44",
             @"GD" : @"+1473",
             @"GE" : @"+995",
             @"GH" : @"+233",
             @"GI" : @"+350",
             @"GL" : @"+299",
             @"GM" : @"+220",
             @"GN" : @"+224",
             @"GQ" : @"+240",
             @"GR" : @"+30",
             @"GT" : @"+502",
             @"GU" : @"+1671",
             @"GW" : @"+245",
             @"GY" : @"+592",
             @"HK" : @"+852",
             @"HN" : @"+504",
             @"HR" : @"+385",
             @"HT" : @"+509",
             @"HU" : @"+36",
             @"ID" : @"+62",
             @"IE" : @"+353",
             @"IL" : @"+972",
             @"IM" : @"+44",
             @"IN" : @"+91",
             @"IQ" : @"+964",
             @"IR" : @"+98",
             @"IS" : @"+354",
             @"IT" : @"+39",
             @"JM" : @"+1876",
             @"JO" : @"+962",
             @"JP" : @"+81",
             @"KE" : @"+254",
             @"KG" : @"+996",
             @"KH" : @"+855",
             @"KI" : @"+686",
             @"KM" : @"+269",
             @"KN" : @"+1869",
             @"KP" : @"+850",
             @"KR" : @"+82",
             @"KW" : @"+965",
             @"KY" : @"+1345",
             @"KZ" : @"+7",
             @"LA" : @"+856",
             @"LB" : @"+961",
             @"LC" : @"+1758",
             @"LI" : @"+423",
             @"LK" : @"+94",
             @"LR" : @"+231",
             @"LS" : @"+266",
             @"LT" : @"+370",
             @"LU" : @"+352",
             @"LV" : @"+371",
             @"LY" : @"+218",
             @"MA" : @"+212",
             @"MC" : @"+377",
             @"MD" : @"+373",
             @"ME" : @"+382",
             @"MF" : @"+1599",
             @"MG" : @"+261",
             @"MH" : @"+692",
             @"MK" : @"+389",
             @"ML" : @"+223",
             @"MM" : @"+95",
             @"MN" : @"+976",
             @"MO" : @"+853",
             @"MP" : @"+1670",
             @"MR" : @"+222",
             @"MS" : @"+1664",
             @"MT" : @"+356",
             @"MU" : @"+230",
             @"MV" : @"+960",
             @"MW" : @"+265",
             @"MX" : @"+52",
             @"MY" : @"+60",
             @"MZ" : @"+258",
             @"NA" : @"+264",
             @"NC" : @"+687",
             @"NE" : @"+227",
             @"NG" : @"+234",
             @"NI" : @"+505",
             @"NL" : @"+31",
             @"NO" : @"+47",
             @"NP" : @"+977",
             @"NR" : @"+674",
             @"NU" : @"+683",
             @"NZ" : @"+64",
             @"OM" : @"+968",
             @"PA" : @"+507",
             @"PE" : @"+51",
             @"PF" : @"+689",
             @"PG" : @"+675",
             @"PH" : @"+63",
             @"PK" : @"+92",
             @"PL" : @"+48",
             @"PM" : @"+508",
             @"PN" : @"+870",
             @"PR" : @"+1",
             @"PT" : @"+351",
             @"PW" : @"+680",
             @"PY" : @"+595",
             @"QA" : @"+974",
             @"RO" : @"+40",
             @"RS" : @"+381",
             @"RU" : @"+7",
             @"RW" : @"+250",
             @"SA" : @"+966",
             @"SB" : @"+677",
             @"SC" : @"+248",
             @"SD" : @"+249",
             @"SE" : @"+46",
             @"SG" : @"+65",
             @"SH" : @"+290",
             @"SI" : @"+386",
             @"SK" : @"+421",
             @"SL" : @"+232",
             @"SM" : @"+378",
             @"SN" : @"+221",
             @"SO" : @"+252",
             @"SR" : @"+597",
             @"ST" : @"+239",
             @"SV" : @"+503",
             @"SY" : @"+963",
             @"SZ" : @"+268",
             @"TC" : @"+1649",
             @"TD" : @"+235",
             @"TG" : @"+228",
             @"TH" : @"+66",
             @"TJ" : @"+992",
             @"TK" : @"+690",
             @"TL" : @"+670",
             @"TM" : @"+993",
             @"TN" : @"+216",
             @"TO" : @"+676",
             @"TR" : @"+90",
             @"TT" : @"+1868",
             @"TV" : @"+688",
             @"TW" : @"+886",
             @"TZ" : @"+255",
             @"UA" : @"+380",
             @"UG" : @"+256",
             @"US" : @"+1",
             @"UY" : @"+598",
             @"UZ" : @"+998",
             @"VA" : @"+39",
             @"VC" : @"+1784",
             @"VE" : @"+58",
             @"VG" : @"+1284",
             @"VI" : @"+1340",
             @"VN" : @"+84",
             @"VU" : @"+678",
             @"WF" : @"+681",
             @"WS" : @"+685",
             @"YE" : @"+967",
             @"YT" : @"+262",
             @"ZA" : @"+27",
             @"ZM" : @"+260",
             @"ZW" : @"+263",
             };
}

- (NSDictionary *)callingCode
{
    return [NSDictionary dictionaryWithObjectsAndKeys:
            @"Canada"                                       , @"+1 ",
            @"China"                                        , @"+86",
            @"France"                                       , @"+33",
            @"Germany"                                      , @"+49",
            @"India"                                        , @"+91",
            @"Japan"                                        , @"+81",
            @"Pakistan"                                     , @"+92",
            @"United Kingdom"                               , @"+44",
            @"United States"                                , @"+1",
            @"Abkhazia"                                     , @"+7 840",
            @"Abkhazia"                                     , @"+7 940",
            @"Afghanistan"                                  , @"+93",
            @"Albania"                                      , @"+355",
            @"Åland Islands"                                , @"+358",
            @"Algeria"                                      , @"+213",
            @"American Samoa"                               , @"+1 684",
            @"Andorra"                                      , @"+376",
            @"Angola"                                       , @"+244",
            @"Antarctica"                                   , @"+672",
            @"Anguilla"                                     , @"+1 264",
            @"Antigua and Barbuda"                          , @"+1 268",
            @"Argentina"                                    , @"+54",
            @"Armenia"                                      , @"+374",
            @"Aruba"                                        , @"+297",
            @"Ascension"                                    , @"+247",
            @"Australia"                                    , @"+61",
            @"Australian External Territories"              , @"+672",
            @"Austria"                                      , @"+43",
            @"Azerbaijan"                                   , @"+994",
            @"Bahamas"                                      , @"+1 242",
            @"Bahrain"                                      , @"+973",
            @"Bangladesh"                                   , @"+880",
            @"Barbados"                                     , @"+1 246",
            @"Barbuda"                                      , @"+1 268",
            @"Belarus"                                      , @"+375",
            @"Belgium"                                      , @"+32",
            @"Belize"                                       , @"+501",
            @"Benin"                                        , @"+229",
            @"Bermuda"                                      , @"+1 441",
            @"Bhutan"                                       , @"+975",
            @"Bolivia"                                      , @"+591",
            @"Bosnia and Herzegovina"                       , @"+387",
            @"Botswana"                                     , @"+267",
            @"Bouvet Island"                                , @"+55",
            @"Brazil"                                       , @"+55",
            @"British Indian Ocean Territory"               , @"+246",
            @"British Virgin Islands"                       , @"+1 284",
            @"Brunei"                                       , @"+673",
            @"Bulgaria"                                     , @"+359",
            @"Burkina Faso"                                 , @"+226",
            @"Burundi"                                      , @"+257",
            @"Cambodia"                                     , @"+855",
            @"Cameroon"                                     , @"+237",
            @"Canada"                                       , @"+1",
            @"Cape Verde"                                   , @"+238",
            @"Caribbean Netherlands"                        , @"+599",
            @"Cayman Islands"                               , @"+ 345",
            @"Central African Republic"                     , @"+236",
            @"Chad"                                         , @"+235",
            @"Chile"                                        , @"+56",
            @"China"                                        , @"+86",
            @"Christmas Island"                             , @"+61",
            @"Cocos (Keeling) Islands"                      , @"+61",
            @"Colombia"                                     , @"+57",
            @"Comoros"                                      , @"+269",
            @"Congo - Brazzaville"                          , @"+242",
            @"Congo - Kinshasa"                             , @"+243",
            @"Cook Islands"                                 , @"+682",
            @"Costa Rica"                                   , @"+506",
            @"Côte d’Ivoire"                                , @"+225",
            @"Croatia"                                      , @"+385",
            @"Cuba"                                         , @"+53",
            @"Curaçao"                                      , @"+599",
            @"Cyprus"                                       , @"+537",
            @"Czech Republic"                               , @"+420",
            @"Denmark"                                      , @"+45",
            @"Diego Garcia"                                 , @"+246",
            @"Djibouti"                                     , @"+253",
            @"Dominica"                                     , @"+1 767",
            @"Dominican Republic"                           , @"+1 809",
            @"Dominican Republic"                           , @"+1 829",
            @"Dominican Republic"                           , @"+1 849",
            @"East Timor"                                   , @"+670",
            @"Easter Island"                                , @"+56",
            @"Ecuador"                                      , @"+593",
            @"Egypt"                                        , @"+20",
            @"El Salvador"                                  , @"+503",
            @"Equatorial Guinea"                            , @"+240",
            @"Eritrea"                                      , @"+291",
            @"Estonia"                                      , @"+372",
            @"Ethiopia"                                     , @"+251",
            @"Falkland Islands"                             , @"+500",
            @"Faroe Islands"                                , @"+298",
            @"Fiji"                                         , @"+679",
            @"Finland"                                      , @"+358",
            @"France"                                       , @"+33",
            @"French Antilles"                              , @"+596",
            @"French Guiana"                                , @"+594",
            @"French Southern Territories"                  , @"+689",
            @"French Polynesia"                             , @"+689",
            @"Gabon"                                        , @"+241",
            @"Gambia"                                       , @"+220",
            @"Georgia"                                      , @"+995",
            @"Germany"                                      , @"+49",
            @"Ghana"                                        , @"+233",
            @"Gibraltar"                                    , @"+350",
            @"Greece"                                       , @"+30",
            @"Greenland"                                    , @"+299",
            @"Grenada"                                      , @"+1 473",
            @"Guadeloupe"                                   , @"+590",
            @"Guam"                                         , @"+1 671",
            @"Guatemala"                                    , @"+502",
            @"Guernsey"                                     , @"+44",
            @"Guinea"                                       , @"+224",
            @"Guinea-Bissau"                                , @"+245",
            @"Guyana"                                       , @"+595",
            @"Haiti"                                        , @"+509",
            @"Honduras"                                     , @"+504",
            @"Heard & McDonald Islands"                     , @"",
            @"Hong Kong SAR China"                          , @"+852",
            @"Hungary"                                      , @"+36",
            @"Iceland"                                      , @"+354",
            @"Isle of Man"                                  , @"+44",
            @"India"                                        , @"+91",
            @"Indonesia"                                    , @"+62",
            @"Iran"                                         , @"+98",
            @"Iraq"                                         , @"+964",
            @"Ireland"                                      , @"+353",
            @"Israel"                                       , @"+972",
            @"Italy"                                        , @"+39",
            @"Jamaica"                                      , @"+1 876",
            @"Japan"                                        , @"+81",
            @"Jersey"                                       , @"+44",
            @"Jordan"                                       , @"+962",
            @"Kazakhstan"                                   , @"+77",
            @"Kenya"                                        , @"+254",
            @"Kiribati"                                     , @"+686",
            @"North Korea"                                  , @"+850",
            @"South Korea"                                  , @"+82",
            @"Kuwait"                                       , @"+965",
            @"Kyrgyzstan"                                   , @"+996",
            @"Laos"                                         , @"+856",
            @"Latvia"                                       , @"+371",
            @"Lebanon"                                      , @"+961",
            @"Lesotho"                                      , @"+266",
            @"Liberia"                                      , @"+231",
            @"Libya"                                        , @"+218",
            @"Liechtenstein"                                , @"+423",
            @"Lithuania"                                    , @"+370",
            @"Luxembourg"                                   , @"+352",
            @"Macau SAR China"                              , @"+853",
            @"Macedonia"                                    , @"+389",
            @"Madagascar"                                   , @"+261",
            @"Malawi"                                       , @"+265",
            @"Malaysia"                                     , @"+60",
            @"Maldives"                                     , @"+960",
            @"Mali"                                         , @"+223",
            @"Malta"                                        , @"+356",
            @"Marshall Islands"                             , @"+692",
            @"Martinique"                                   , @"+596",
            @"Mauritania"                                   , @"+222",
            @"Mauritius"                                    , @"+230",
            @"Mayotte"                                      , @"+262",
            @"Mexico"                                       , @"+52",
            @"Micronesia"                                   , @"+691",
            @"Midway Island"                                , @"+1 808",
            @"Micronesia"                                   , @"+691",
            @"Moldova"                                      , @"+373",
            @"Monaco"                                       , @"+377",
            @"Mongolia"                                     , @"+976",
            @"Montenegro"                                   , @"+382",
            @"Montserrat"                                   , @"+1664",
            @"Morocco"                                      , @"+212",
            @"Mozambique"                                   , @"+258",
            @"Myanmar (Burma)"                              , @"+95",
            @"Namibia"                                      , @"+264",
            @"Nauru"                                        , @"+674",
            @"Nepal"                                        , @"+977",
            @"Netherlands"                                  , @"+31",
            @"Netherlands Antilles"                         , @"+599",
            @"Nevis"                                        , @"+1 869",
            @"New Caledonia"                                , @"+687",
            @"New Zealand"                                  , @"+64",
            @"Nicaragua"                                    , @"+505",
            @"Niger"                                        , @"+227",
            @"Nigeria"                                      , @"+234",
            @"Niue"                                         , @"+683",
            @"Norfolk Island"                               , @"+672",
            @"Northern Mariana Islands"                     , @"+1 670",
            @"Norway"                                       , @"+47",
            @"Oman"                                         , @"+968",
            @"Pakistan"                                     , @"+92",
            @"Palau"                                        , @"+680",
            @"Palestinian Territories"                      , @"+970",
            @"Panama"                                       , @"+507",
            @"Papua New Guinea"                             , @"+675",
            @"Paraguay"                                     , @"+595",
            @"Peru"                                         , @"+51",
            @"Philippines"                                  , @"+63",
            @"Pitcairn Islands"                             , @"+64",
            @"Poland"                                       , @"+48",
            @"Portugal"                                     , @"+351",
            @"Puerto Rico"                                  , @"+1",
            @"Qatar"                                        , @"+974",
            @"Réunion"                                      , @"+262",
            @"Romania"                                      , @"+40",
            @"Russia"                                       , @"+7",
            @"Rwanda"                                       , @"+250",
            @"Samoa"                                        , @"+685",
            @"San Marino"                                   , @"+378",
            @"Saint Barthélemy"                             , @"+590",
            @"São Tomé and Príncipe"                        , @"+239",
            @"Saint Helena"                                 , @"+290",
            @"Saint Kitts and Nevis"                        , @"+1 721",
            @"Saint Pierre and Miquelon"                    , @"+508",
            @"Saint Lucia"                                  , @"+1 758",
            @"Saudi Arabia"                                 , @"+966",
            @"Senegal"                                      , @"+221",
            @"Serbia"                                       , @"+381",
            @"Seychelles"                                   , @"+248",
            @"Sierra Leone"                                 , @"+232",
            @"Singapore"                                    , @"+65",
            @"Sint Martin"                                  , @"+1 721",
            @"Slovakia"                                     , @"+421",
            @"Slovenia"                                     , @"+386",
            @"Solomon Islands"                              , @"+677",
            @"Somalia"                                      , @"+252",
            @"South Africa"                                 , @"+27",
            @"South Sudan"                                  , @"+211",
            @"So. Georgia & So. Sandwich Isl."              , @"+500",
            @"Spain"                                        , @"+34",
            @"Sri Lanka"                                    , @"+94",
            @"St. Vincent & Grenadines"                     , @"+ 1 784 ",
            @"Sudan"                                        , @"+249",
            @"Suriname"                                     , @"+597",
            @"Svalbard and Jan Mayen"                       , @"+47",
            @"Swaziland"                                    , @"+268",
            @"Sweden"                                       , @"+46",
            @"Switzerland"                                  , @"+41",
            @"Syria"                                        , @"+963",
            @"Taiwan"                                       , @"+886",
            @"Tajikistan"                                   , @"+992",
            @"Tanzania"                                     , @"+255",
            @"Thailand"                                     , @"+66",
            @"Timor-Leste"                                  , @"+670",
            @"Togo"                                         , @"+228",
            @"Tokelau"                                      , @"+690",
            @"Tonga"                                        , @"+676",
            @"Trinidad and Tobago"                          , @"+1 868",
            @"Tunisia"                                      , @"+216",
            @"Turkey"                                       , @"+90",
            @"Turkmenistan"                                 , @"+993",
            @"Turks and Caicos Islands"                     , @"+1 649",
            @"Tuvalu"                                       , @"+688",
            @"Uganda"                                       , @"+256",
            @"Ukraine"                                      , @"+380",
            @"United Arab Emirates"                         , @"+971",
            @"United Kingdom"                               , @"+44",
            @"United States"                                , @"+1",
            @"Uruguay"                                      , @"+598",
            @"U.S. Outlying Islands"                        , @"+1",
            @"U.S. Virgin Islands"                          , @"+1 340",
            @"Uzbekistan"                                   , @"+998",
            @"Vanuatu"                                      , @"+678",
            @"Venezuela"                                    , @"+58",
            @"Vatican City"                                 , @"+39",
            @"Vietnam"                                      , @"+84",
            @"Wake Island"                                  , @"+1 808",
            @"Wallis and Futuna"                            , @"+681",
            @"Western Sahara"                               , @"+212",
            @"Yemen"                                        , @"+967",
            @"Zambia"                                       , @"+260",
            @"Zanzibar"                                     , @"+255",
            @"Zimbabwe"                                     , @"+263",
             nil];
}

- (NSDictionary *)countryByCode
{
  return  [NSDictionary dictionaryWithObjectsAndKeys:
  @[@"Afghanistan",@"93"],@"AF",
  @[@"Aland Islands",@"358"],@"AX",
  @[@"Albania",@"355"],@"AL",
  @[@"Algeria",@"213"],@"DZ",
  @[@"American Samoa",@"1"],@"AS",
  @[@"Andorra",@"376"],@"AD",
  @[@"Angola",@"244"],@"AO",
  @[@"Anguilla",@"1"],@"AI",
  @[@"Antarctica",@"672"],@"AQ",
  @[@"Antigua and Barbuda",@"1"],@"AG",
  @[@"Argentina",@"54"],@"AR",
  @[@"Armenia",@"374"],@"AM",
  @[@"Aruba",@"297"],@"AW",
  @[@"Australia",@"61"],@"AU",
  @[@"Austria",@"43"],@"AT",
  @[@"Azerbaijan",@"994"],@"AZ",
  @[@"Bahamas",@"1"],@"BS",
  @[@"Bahrain",@"973"],@"BH",
  @[@"Bangladesh",@"880"],@"BD",
  @[@"Barbados",@"1"],@"BB",
  @[@"Belarus",@"375"],@"BY",
  @[@"Belgium",@"32"],@"BE",
  @[@"Belize",@"501"],@"BZ",
  @[@"Benin",@"229"],@"BJ",
  @[@"Bermuda",@"1"],@"BM",
  @[@"Bhutan",@"975"],@"BT",
  @[@"Bolivia",@"591"],@"BO",
  @[@"Bosnia and Herzegovina",@"387"],@"BA",
  @[@"Botswana",@"267"],@"BW",
  @[@"Bouvet Island",@"47"],@"BV",
  @[@"BQ",@"599"],@"BQ",
  @[@"Brazil",@"55"],@"BR",
  @[@"British Indian Ocean Territory",@"246"],@"IO",
  @[@"British Virgin Islands",@"1"],@"VG",
  @[@"Brunei Darussalam",@"673"],@"BN",
  @[@"Bulgaria",@"359"],@"BG",
  @[@"Burkina Faso",@"226"],@"BF",
  @[@"Burundi",@"257"],@"BI",
  @[@"Cambodia",@"855"],@"KH",
  @[@"Cameroon",@"237"],@"CM",
  @[@"Canada",@"1"],@"CA",
  @[@"Cape Verde",@"238"],@"CV",
  @[@"Cayman Islands",@"345"],@"KY",
  @[@"Central African Republic",@"236"],@"CF",
  @[@"Chad",@"235"],@"TD",
  @[@"Chile",@"56"],@"CL",
  @[@"China",@"86"],@"CN",
  @[@"Christmas Island",@"61"],@"CX",
  @[@"Cocos (Keeling) Islands",@"61"],@"CC",
  @[@"Colombia",@"57"],@"CO",
  @[@"Comoros",@"269"],@"KM",
  @[@"Congo (Brazzaville)",@"242"],@"CG",
  @[@"Congo, Democratic Republic of the",@"243"],@"CD",
  @[@"Cook Islands",@"682"],@"CK",
  @[@"Costa Rica",@"506"],@"CR",
  @[@"Côte d'Ivoire",@"225"],@"CI",
  @[@"Croatia",@"385"],@"HR",
  @[@"Cuba",@"53"],@"CU",
  @[@"Curacao",@"599"],@"CW",
  @[@"Cyprus",@"537"],@"CY",
  @[@"Czech Republic",@"420"],@"CZ",
  @[@"Denmark",@"45"],@"DK",
  @[@"Djibouti",@"253"],@"DJ",
  @[@"Dominica",@"1"],@"DM",
  @[@"Dominican Republic",@"1"],@"DO",
  @[@"Ecuador",@"593"],@"EC",
  @[@"Egypt",@"20"],@"EG",
  @[@"El Salvador",@"503"],@"SV",
  @[@"Equatorial Guinea",@"240"],@"GQ",
  @[@"Eritrea",@"291"],@"ER",
  @[@"Estonia",@"372"],@"EE",
  @[@"Ethiopia",@"251"],@"ET",
  @[@"Falkland Islands (Malvinas)",@"500"],@"FK",
  @[@"Faroe Islands",@"298"],@"FO",
  @[@"Fiji",@"679"],@"FJ",
  @[@"Finland",@"358"],@"FI",
  @[@"France",@"33"],@"FR",
  @[@"French Guiana",@"594"],@"GF",
  @[@"French Polynesia",@"689"],@"PF",
  @[@"French Southern Territories",@"689"],@"TF",
  @[@"Gabon",@"241"],@"GA",
  @[@"Gambia",@"220"],@"GM",
  @[@"Georgia",@"995"],@"GE",
  @[@"Germany",@"49"],@"DE",
  @[@"Ghana",@"233"],@"GH",
  @[@"Gibraltar",@"350"],@"GI",
  @[@"Greece",@"30"],@"GR",
  @[@"Greenland",@"299"],@"GL",
  @[@"Grenada",@"1"],@"GD",
  @[@"Guadeloupe",@"590"],@"GP",
  @[@"Guam",@"1"],@"GU",
  @[@"Guatemala",@"502"],@"GT",
  @[@"Guernsey",@"44"],@"GG",
  @[@"Guinea",@"224"],@"GN",
  @[@"Guinea-Bissau",@"245"],@"GW",
  @[@"Guyana",@"595"],@"GY",
  @[@"Haiti",@"509"],@"HT",
  @[@"Holy See (Vatican City State)",@"379"],@"VA",
  @[@"Honduras",@"504"],@"HN",
  @[@"Hong Kong, Special Administrative Region of China",@"852"],@"HK",
  @[@"Hungary",@"36"],@"HU",
  @[@"Iceland",@"354"],@"IS",
  @[@"India",@"91"],@"IN",
  @[@"Indonesia",@"62"],@"ID",
  @[@"Iran, Islamic Republic of",@"98"],@"IR",
  @[@"Iraq",@"964"],@"IQ",
  @[@"Ireland",@"353"],@"IE",
  @[@"Isle of Man",@"44"],@"IM",
  @[@"Israel",@"972"],@"IL",
  @[@"Italy",@"39"],@"IT",
  @[@"Jamaica",@"1"],@"JM",
  @[@"Japan",@"81"],@"JP",
  @[@"Jersey",@"44"],@"JE",
  @[@"Jordan",@"962"],@"JO",
  @[@"Kazakhstan",@"77"],@"KZ",
  @[@"Kenya",@"254"],@"KE",
  @[@"Kiribati",@"686"],@"KI",
  @[@"Korea, Democratic People's Republic of",@"850"],@"KP",
  @[@"Korea, Republic of",@"82"],@"KR",
  @[@"Kuwait",@"965"],@"KW",
  @[@"Kyrgyzstan",@"996"],@"KG",
  @[@"Lao PDR",@"856"],@"LA",
  @[@"Latvia",@"371"],@"LV",
  @[@"Lebanon",@"961"],@"LB",
  @[@"Lesotho",@"266"],@"LS",
  @[@"Liberia",@"231"],@"LR",
  @[@"Libya",@"218"],@"LY",
  @[@"Liechtenstein",@"423"],@"LI",
  @[@"Lithuania",@"370"],@"LT",
  @[@"Luxembourg",@"352"],@"LU",
  @[@"Macao, Special Administrative Region of China",@"853"],@"MO",
  @[@"Macedonia, Republic of",@"389"],@"MK",
  @[@"Madagascar",@"261"],@"MG",
  @[@"Malawi",@"265"],@"MW",
  @[@"Malaysia",@"60"],@"MY",
  @[@"Maldives",@"960"],@"MV",
  @[@"Mali",@"223"],@"ML",
  @[@"Malta",@"356"],@"MT",
  @[@"Marshall Islands",@"692"],@"MH",
  @[@"Martinique",@"596"],@"MQ",
  @[@"Mauritania",@"222"],@"MR",
  @[@"Mauritius",@"230"],@"MU",
  @[@"Mayotte",@"262"],@"YT",
  @[@"Mexico",@"52"],@"MX",
  @[@"Micronesia, Federated States of",@"691"],@"FM",
  @[@"Moldova",@"373"],@"MD",
  @[@"Monaco",@"377"],@"MC",
  @[@"Mongolia",@"976"],@"MN",
  @[@"Montenegro",@"382"],@"ME",
  @[@"Montserrat",@"1"],@"MS",
  @[@"Morocco",@"212"],@"MA",
  @[@"Mozambique",@"258"],@"MZ",
  @[@"Myanmar",@"95"],@"MM",
  @[@"Namibia",@"264"],@"NA",
  @[@"Nauru",@"674"],@"NR",
  @[@"Nepal",@"977"],@"NP",
  @[@"Netherlands",@"31"],@"NL",
  @[@"Netherlands Antilles",@"599"],@"AN",
  @[@"New Caledonia",@"687"],@"NC",
  @[@"New Zealand",@"64"],@"NZ",
  @[@"Nicaragua",@"505"],@"NI",
  @[@"Niger",@"227"],@"NE",
  @[@"Nigeria",@"234"],@"NG",
  @[@"Niue",@"683"],@"NU",
  @[@"Norfolk Island",@"672"],@"NF",
  @[@"Northern Mariana Islands",@"1"],@"MP",
  @[@"Norway",@"47"],@"NO",
  @[@"Oman",@"968"],@"OM",
  @[@"Pakistan",@"92"],@"PK",
  @[@"Palau",@"680"],@"PW",
  @[@"Palestinian Territory, Occupied",@"970"],@"PS",
  @[@"Panama",@"507"],@"PA",
  @[@"Papua New Guinea",@"675"],@"PG",
  @[@"Paraguay",@"595"],@"PY",
  @[@"Peru",@"51"],@"PE",
  @[@"Philippines",@"63"],@"PH",
  @[@"Pitcairn",@"872"],@"PN",
  @[@"Poland",@"48"],@"PL",
  @[@"Portugal",@"351"],@"PT",
  @[@"Puerto Rico",@"1"],@"PR",
  @[@"Qatar",@"974"],@"QA",
  @[@"Réunion",@"262"],@"RE",
  @[@"Romania",@"40"],@"RO",
  @[@"Russian Federation",@"7"],@"RU",
  @[@"Rwanda",@"250"],@"RW",
  @[@"Saint Helena",@"290"],@"SH",
  @[@"Saint Kitts and Nevis",@"1"],@"KN",
  @[@"Saint Lucia",@"1"],@"LC",
  @[@"Saint Pierre and Miquelon",@"508"],@"PM",
  @[@"Saint Vincent and Grenadines",@"1"],@"VC",
  @[@"Saint-Barthélemy",@"590"],@"BL",
  @[@"Saint-Martin (French part)",@"590"],@"MF",
  @[@"Samoa",@"685"],@"WS",
  @[@"San Marino",@"378"],@"SM",
  @[@"Sao Tome and Principe",@"239"],@"ST",
  @[@"Saudi Arabia",@"966"],@"SA",
  @[@"Senegal",@"221"],@"SN",
  @[@"Serbia",@"381"],@"RS",
  @[@"Seychelles",@"248"],@"SC",
  @[@"Sierra Leone",@"232"],@"SL",
  @[@"Singapore",@"65"],@"SG",
  @[@"Sint Maarten",@"1"],@"SX",
  @[@"Slovakia",@"421"],@"SK",
  @[@"Slovenia",@"386"],@"SI",
  @[@"Solomon Islands",@"677"],@"SB",
  @[@"Somalia",@"252"],@"SO",
  @[@"South Africa",@"27"],@"ZA",
  @[@"South Georgia and the South Sandwich Islands",@"500"],@"GS",
  @[@"South Sudan",@"211"],@"SS​",
  @[@"Spain",@"34"],@"ES",
  @[@"Sri Lanka",@"94"],@"LK",
  @[@"Sudan",@"249"],@"SD",
  @[@"Suriname",@"597"],@"SR",
  @[@"Svalbard and Jan Mayen Islands",@"47"],@"SJ",
  @[@"Swaziland",@"268"],@"SZ",
  @[@"Sweden",@"46"],@"SE",
  @[@"Switzerland",@"41"],@"CH",
  @[@"Syrian Arab Republic (Syria)",@"963"],@"SY",
  @[@"Taiwan, Republic of China",@"886"],@"TW",
  @[@"Tajikistan",@"992"],@"TJ",
  @[@"Tanzania, United Republic of",@"255"],@"TZ",
  @[@"Thailand",@"66"],@"TH",
  @[@"Timor-Leste",@"670"],@"TL",
  @[@"Togo",@"228"],@"TG",
  @[@"Tokelau",@"690"],@"TK",
  @[@"Tonga",@"676"],@"TO",
  @[@"Trinidad and Tobago",@"1"],@"TT",
  @[@"Tunisia",@"216"],@"TN",
  @[@"Turkey",@"90"],@"TR",
  @[@"Turkmenistan",@"993"],@"TM",
  @[@"Turks and Caicos Islands",@"1"],@"TC",
  @[@"Tuvalu",@"688"],@"TV",
  @[@"Uganda",@"256"],@"UG",
  @[@"Ukraine",@"380"],@"UA",
  @[@"United Arab Emirates",@"971"],@"AE",
  @[@"United Kingdom",@"44"],@"GB",
  @[@"United States of America",@"1"],@"US",
  @[@"Uruguay",@"598"],@"UY",
  @[@"Uzbekistan",@"998"],@"UZ",
  @[@"Vanuatu",@"678"],@"VU",
  @[@"Venezuela (Bolivarian Republic of)",@"58"],@"VE",
  @[@"Viet Nam",@"84"],@"VN",
  @[@"Virgin Islands, US",@"1"],@"VI",
  @[@"Wallis and Futuna Islands",@"681"],@"WF",
  @[@"Western Sahara",@"212"],@"EH",
  @[@"Yemen",@"967"],@"YE",
  @[@"Zambia",@"260"],@"ZM",
  @[@"Zimbabwe",@"263"],@"ZW", nil];
}

- (NSString *)countryCallingCode
{
    NSString *key = [self.isoCountryCode uppercaseString];
    return self.callingCodeMap[key];
}
- (NSString *)countryCallingCode:(NSString *)code
{
    return self.callingCode[code];
}
- (NSArray *)countryCalling
{
    
    NSString *key = [self.isoCountryCode uppercaseString];
    return self.countryByCode[key];
}

@end